#!/usr/bin/env tsx
/**
 * One-time OAuth2 consent flow for Gmail API.
 *
 * Usage:
 *   pnpm email:auth
 *   npx tsx email/cli-auth.ts
 *
 * Prerequisites:
 *   1. Create a Google Cloud project and enable the Gmail API
 *   2. Create OAuth2 credentials (Desktop app type)
 *   3. Download as email/credentials.json
 */

import { createServer } from "http";
import { URL } from "url";
import { writeFileSync } from "fs";
import { execFile } from "child_process";
import { google } from "googleapis";
import { loadCredentials, SCOPES, TOKEN_PATH } from "./gmail.ts";

const PORT = 3000;
const REDIRECT_URI = `http://localhost:${PORT}/oauth2callback`;

async function main(): Promise<void> {
  const creds = loadCredentials();
  const { client_id, client_secret } = creds.installed;

  const oauth2 = new google.auth.OAuth2(client_id, client_secret, REDIRECT_URI);

  const authUrl = oauth2.generateAuthUrl({
    access_type: "offline",
    scope: SCOPES,
    prompt: "consent",
  });

  console.log("\nOpening browser for Google OAuth2 consent...\n");
  console.log(`If the browser doesn't open, visit:\n${authUrl}\n`);

  // Open browser (safe: authUrl is generated by us, not user input)
  const cmd =
    process.platform === "darwin"
      ? "open"
      : process.platform === "win32"
        ? "start"
        : "xdg-open";
  execFile(cmd, [authUrl]);

  // Start local server to receive the callback
  const code = await waitForAuthCode();

  console.log("Exchanging auth code for tokens...");
  const { tokens } = await oauth2.getToken(code);
  writeFileSync(TOKEN_PATH, JSON.stringify(tokens, null, 2) + "\n");

  console.log(`\nToken saved to ${TOKEN_PATH}`);
  console.log("Gmail API is ready to use.");
  process.exit(0);
}

function waitForAuthCode(): Promise<string> {
  return new Promise((resolve, reject) => {
    const server = createServer((req, res) => {
      const url = new URL(req.url ?? "/", `http://localhost:${PORT}`);

      if (url.pathname !== "/oauth2callback") {
        res.writeHead(404);
        res.end("Not found");
        return;
      }

      const code = url.searchParams.get("code");
      const error = url.searchParams.get("error");

      if (error) {
        res.writeHead(200, { "Content-Type": "text/html" });
        res.end(`<h1>Authorization failed</h1><p>${error}</p>`);
        server.close();
        reject(new Error(`OAuth2 error: ${error}`));
        return;
      }

      if (!code) {
        res.writeHead(400, { "Content-Type": "text/html" });
        res.end("<h1>Missing authorization code</h1>");
        return;
      }

      res.writeHead(200, { "Content-Type": "text/html" });
      res.end(
        "<h1>Authorization successful!</h1><p>You can close this tab and return to the terminal.</p>"
      );
      server.close();
      resolve(code);
    });

    server.listen(PORT, () => {
      console.log(`Waiting for OAuth2 callback on http://localhost:${PORT}...`);
    });

    server.on("error", (err) => {
      reject(new Error(`Could not start callback server: ${err.message}`));
    });
  });
}

main().catch((err) => {
  console.error("Auth failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
